dag_id: "ingesta_datos_ventas"
schedule: "0 5 * * *" 
description: "Pipeline de ejemplo para la ingesta de datos usando Dataproc ef√≠mero"
script_path: "scripts/ejemplo_ingesta.py"

cluster_config:
  region: "us-central1"
  master_machine_type: "n1-standard-2"
  worker_machine_type: "n1-standard-2"
  num_workers: 2
  image_version: "2.1-debian11"

dependencies:
  - pandas
  - requests
